language: node_js
node_js:
- '0.10'
before_install:
- npm install -g bower
- npm install -g grunt-cli
install:
- npm install
- grunt build
after_success:
- cd dist/ && tar -zcf ../wilson-docs-dist-$TRAVIS_BRANCH.tar.gz . && cd ..
deploy:
  provider: releases
  file: wilson-docs-dist-$TRAVIS_BRANCH.tar.gz
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
  api-key:
    secure: CjvsNt/pkJMlv+iIwS4N6i0ia0HGsI95O8go1pIpz2wHRl+7xKdt6FAfcMYqvPP7bhlg62rcnvx8gsxBnX2OdYNwZyG1Jfg8SlczlEJl/ynFfGikYQqakU7e0Sld9KF8hXUYXktf8K+UwhSVz/FvdDeM4Guh+UbXXhaTDdTITYNVYP8upwrd7JzBQUD2Li61wzOPIsIFUvZ1NZ7wFbfrQ6x7ltF2eGKfYqh4Lbt9hpIzft5CPOdV7Tqm881pqh8+GQcGYM5wT4oM57GTpyWbctG6pnOEqW+L7F/dtv2WE8hdB8bvN+lu37Sj2Q6BIXjNcFbY1UCzDZlyvlPojKN5LKlln4KSsX0ebS+X3TTizLA3XcqUmGyaBjKgruOhvx6QRjoaG6BdH3ki2b/RiY/4eCgY0e5tx6D7FKQ8QWJytfw+0CMeFNacuPI8aDFRnqpoKpnrBb3KyDwdM+RdTLQGFy7NgZzcjcsiVNeu3HTZ4I/H/pY3RdQgkxMDUzIEbs+rufRQm4MSxl3UZCl8HqhRyOoq6aGbna856FnilOadY28tY2PC4OEcQpcYGSXGaj0u3JL40SzZ2PJzHsL31VJiRLxn3Hx+ve+RxE1u6l3XE3tx1Xl23sl/AeCtYMlLLyQJoEVy11NwSY1RqRKgoCxL5Ky+qWrDxy0uKLqS76v1L8I=
notifications:
  hipchat:
    rooms:
    - C078QI8sp1gTzi4y0nUP64LiQz7Z26WCERJFhmNS@842637
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
  slack:
    secure: g1HHopACLVx5vAZ6TB6j0uXQVxvlMUQsJSrTKbpOb9V73bE7Mq64BjcNOfBzrF03df8ML0B7T7yiFxfnJPJcWIetFJRCA30GVUHdrXbSgLvyBRUQscHaQQItEcCUH9DaCfTF/AosK4m6AFi//hFbeH7R705ruWnWYXBtqiVyWiw0Yxd3zjLR5CjhqaAPoNqEt2qf+yK+KdYNO8uPHjvsTRpHVMNA6pP4qz6WyvOxP0XW/Bcv/h4tf3PqWizTsUQ0U1U/40Rbj6JiojtqcHKsuTu2IpM3Yfrgsd/xQUG6eQkpS0jHwSJNnDs+he0Ds0aatB6084T4/VliqpZv3pNjCzMpTu7qM+cekhvhdNKs59GF+OpN+Mh7re8/8t4qtVEN9wHBHKhAh+HWbwI3t5FuK4K9udOT9CFlgK9QNrYtLIoouurAbDq96GLuU5A1LhWAkijyL+NtI4IhOFsqrpXDcBt2W4/o9uB0tSeiKAqOSnQ/6IsYA5lKVXw5PdOhxJy/gNM1N8L5RqLrVKupHGGMUsHdM9AayT152B+/4SCimjqziVRPoVPZhMzTEgdmJOXWx9OUaZSQ33evqKsywZQNiezdIp4TbyWRKrYsHQK43qwtQWvzb65XU9/aSGZkQQB+Ux6pLtZhHNp2y0TH11J+vp+3sld7ELwuxMVPyScW3XM=
